# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e824058cb7dc58eb6fcc45e11e4929059133cf4c195b39b8f603149871b91c5e05d1505bb83a67251ab8aa036a1ea4c5af6a672972c19ae136d9737e5d4c4f93

test:
  secret_key_base: f73007f29309acdf5b5e25ddd87ca22b6b4cfc07db0c91e8180cc3718c7a7f3e05238a5978bce7bdd36ca474be36e62cfd7482699de39a6129eb04240796803b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
